### PR TITLE
Jens branch

### PR DESCRIPTION
**Pull request by YHDiamond**

### CODE REVIEW

**Comment by Jens-Co** [comment]
Might need some cleanup on this tho.

**Review by YHDiamond — COMMENTED** [review]
Looks good :)

**Comment by Jens-Co** [comment]
Last push was a typo that I made.

**Comment by Jens-Co** [comment]
Also changed version before you changed it. If you merge it could be changed back to version that same version :)

**Comment by YHDiamond** [comment]
version 0.2.5 was bstats

**Comment by YHDiamond** [comment]
maybe we can do some kewl maevn stuf to do that automagically

**Pull request merged**
