### PR TITLE
Update restart script creation and readme

### PR DESCRIPTION
**Pull request by Konicai**
- Optimize imports

- Change the script creation in BungeeUpdater.Java and SpigotUpdater.Java to be more similar and adjust some names to be more unique.

- Implements proper script creation for Spigot/Bungee on Mac/Windows/Linux. Spigot doesn't need a loop in the script, Bungee does. Nothing special.

- Squashed a readme change into this

Probably a handful of formatting and style mistakes, but the script creation performed correctly when I tested it on bungee and spigot.

### CODE REVIEW

**Comment by YHDiamond** [comment]
this looks ok

**Comment by Konicai** [comment]
Latest commit just fixes a conflict caused by a new commit

**Review by Jens-Co — APPROVED** [review]

**Comment by Konicai** [comment]
Still gotta resolve the conflicts

**Review by Jens-Co — COMMENTED** [review]
You got conflicts

**Pull request closed without merging**
